### ISSUE TITLE
Allow user to specify bounding box for cards

### ISSUE THREAD

**Issue by BudgieInWA** [eoakley/artifacthelper#10]
The new dragging feature could be improved to provide a fully user-configurable way of working. Instead of having a drag handle that is always visible, have a "configure" button that switches to "configure mode". While in configure mode, draw a box around the border of the windows and provide handles in the corners. Ask the user to position the box so that all of the cards are inside the box and the banner is above them. Then the detection algorithm can find the exact edges.

The top left handle could act like the drag currently does, and the bottom right handle could scale the rectangle, maintaining the aspect ratio.
![image](https://user-images.githubusercontent.com/3784591/49416741-05e80380-f7b6-11e8-976e-5b35617d157c.png)

This method should work for any configuration that cannot be predicted (like running in a small window) so it might be useful to have, even if all of the common configurations work out of the box.

**Comment by BudgieInWA** [comment]
In fact, I'm basically thinking of [Snipping Tool](https://en.wikipedia.org/wiki/Snipping_Tool).

When the overlay opens it guesses where the cards are (assuming fullscreen borderless and whatever dimensions the game is known to use). By clicking a "locate" button or any time a scan is done and no cards are found, it could immediately switch to "rectangular snip" mode with instructions "Select the Cards" and a cancel button. The dimensions of the rectangle can be used to check for cards in the screenshot and to decide where to put the banner.

If the user failed to draw around the cards properly they could see a gif of someone doing it correctly.

**Comment by eoakley** [comment]
Nice suggestion. Implementing it soon.

**Comment by eoakley** [comment]
Made the border detection algorithm more robust. Should not need to implement custom bounding boxes yet.

**Comment by eoakley** [comment]
Just fixed this in the [latest release](https://github.com/eoakley/artifacthelper/releases/latest).

Try the new function "Customize Grid".

If you still have problems, open a new issue with the following:
* Description of your setup (monitor resolutions)
* Full screenshot (all monitors) 
* File **screenshot_debugg.png** from the install dir
* File Artifact_Helper.launch.pyw.log from the folder C:\Users\<your_user>\AppData\Roaming

Thanks for the help!
