### ISSUE TITLE
Windowsed support

### ISSUE THREAD

**Issue by NicolasConstant** [eoakley/artifacthelper#11]
I have some issues with "borderless window" mode (artifacthelper doesn't stay on top and disappear when clicking on cards). I tried to find why it wasn't working on "windowsed" mode. 
In fact, on windowsed mode there is a little black offset captured with the screen that is messing up with the detection process: 

![screen_shot_debugg](https://user-images.githubusercontent.com/5437247/49421104-8a0d9d00-f75c-11e8-8937-a7031c5e9514.png)

Adding this offset to the grid positioning makes artifacthelper working on "windowsed" mode. :) 
If those modes can't be detected by the app, maybe it could be interesting to provide an app-setting to handle both cases?

**Comment by eoakley** [comment]
Just fixed this in the [latest release](https://github.com/eoakley/artifacthelper/releases/latest).
Now supports windowed mode as well.
Also, you need to restar the game to apply borderless window correctly.

If you still have problems, open a new issue with the following:
* Description of your setup
* Full screenshot (all monitors) 
* File **screen_shot_debugg.png** from the install dir

Thanks for the help!
