### ISSUE TITLE
doesnt work on my laptop

### ISSUE THREAD

**Issue by zeroguz** [eoakley/artifacthelper#12]
![screen_shot_debugg](https://user-images.githubusercontent.com/36460450/49421707-5862f900-f791-11e8-9d44-523e72cb5e63.png)

i run the game on my msi gs 65 on fullhd borderless window mode,
only one monitor... i am guessing it might have something to do with the dual gpu setup the gaming laptops have, the game is running on my dedicated cpu

**Comment by eoakley** [comment]
Just fixed this in the [latest release](https://github.com/eoakley/artifacthelper/releases/latest).

If you still have problems, open a new issue with the following:
* Description of your setup
* Full screenshot (all monitors) 
* File **screen_shot_debugg.png** from the install dir

Thanks for the help!
