### ISSUE TITLE
Still having issues detecting cards.

### ISSUE THREAD

**Issue by emerald000** [eoakley/artifacthelper#13]
I am running in 1960x1080 borderless window. Here's what my full monitor looks like:

![Screenshot](https://i.imgur.com/nP5ucOR.jpg)

I do not have a second monitor. I also do not have a file named screen_shot_debugg.png anywhere in the installation folder (or anywhere else on my computer).

**Comment by eoakley** [comment]
This is a pretty weird case. Please test again and I think it will work on the new release.
Remember to restart game after applying borderless window mode.

[latest release](https://github.com/eoakley/artifacthelper/releases/latest).

If you still have problems, open a new issue with the following:
* Description of your setup
* Full screenshot (all monitors) 
* File **screen_shot_debugg.png** from the install dir

Thanks for the help!
