### ISSUE TITLE
v0.6 works but v0.8 and v0.9 doesnt

### ISSUE THREAD

**Issue by IgorMCesar** [eoakley/artifacthelper#15]
![image](https://user-images.githubusercontent.com/5064518/49474146-18d0f700-f7fb-11e8-8f9d-62a1f3f19a8f.png)

![image](https://user-images.githubusercontent.com/5064518/49474307-7b29f780-f7fb-11e8-9f02-7d38ee159170.png)

Even installed in different folders to make sure it has nothing to do with versioning.

**Comment by eoakley** [comment]
Can you replace the contents of the file "pkgs/artifact_helper.py" with this one? (on the latest release)
[artifact_helper.py](https://github.com/eoakley/artifacthelper/blob/master/artifact_helper.py)

Then relaunch, and press scan cards a couple of times, and then post the log file:
'Artifact_Helper.launch.pyw.log' in the folder C:\Users<your_user>\AppData\Roaming

Thanks

**Comment by IgorMCesar** [comment]
Sure, will just finish this run first =)

**Comment by IgorMCesar** [comment]
> Traceback (most recent call last):
>   File "D:\ArtifactHelper2\Artifact_Helper.launch.pyw", line 31, in <module>
>     from artifact_helper import main
>   File "D:\ArtifactHelper2\pkgs\artifact_helper.py", line 1, in <module>
>     from screen_processor import ScreenProcessor, numpy_flip, save_debugg_screenshot
> ImportError: cannot import name 'save_debugg_screenshot'
>

**Comment by eoakley** [comment]
Do the same process for the file screen_processor.py, overwriting the existing one.

**Comment by IgorMCesar** [comment]
Did it, log is clean :/

**Comment by eoakley** [comment]
Just fixed this in the [latest release](https://github.com/eoakley/artifacthelper/releases/latest).

Try the new function "Customize Grid".

If you still have problems, open a new issue with the following:
* Description of your setup (monitor resolutions)
* Full screenshot (all monitors) 
* File **screenshot_debugg.png** from the install dir
* File Artifact_Helper.launch.pyw.log from the folder C:\Users\<your_user>\AppData\Roaming

Thanks for the help!
