### ISSUE TITLE
Card Detection not working.

### ISSUE THREAD

**Issue by emerald000** [eoakley/artifacthelper#16]
As a follow-up to #13, version v0.9 still isn't working. I tried running from master too (4eaecc0637aa9346db22bc19190f0b55c86214b3) and it's not working either. Here's the output I get from master (after the price collection) from starting the overlay and clicking on "Scan Cards" a couple of times:

```Creating overlay with size: 1920 1080
Detecting grid once... (1080, 1920, 3)
It worked! At least one card is not empty.
['Empty Slot', 'Empty Slot', 'Empty Slot', 'Empty Slot', 'Empty Slot', 'Empty Slot', 'Empty Slot', 'Empty Slot', 'Empty Slot', 'Empty Slot', 'Empty Slot', 'Empty Slot'] (270, 640, 960)
It worked! At least one card is not empty.
['Empty Slot', 'Empty Slot', 'Empty Slot', 'Empty Slot', 'Empty Slot', 'Empty Slot', 'Empty Slot', 'Empty Slot', 'Empty Slot', 'Empty Slot', 'Empty Slot', 'Empty Slot'] (270, 640, 960)
It worked! At least one card is not empty.
['Empty Slot', 'Empty Slot', 'Empty Slot', 'Empty Slot', 'Empty Slot', 'Empty Slot', 'Empty Slot', 'Empty Slot', 'Empty Slot', 'Empty Slot', 'Empty Slot', 'Empty Slot'] (270, 640, 960)

**Comment by eoakley** [comment]
![screen_shot_debugg](https://user-images.githubusercontent.com/1661399/49516227-4318c800-f880-11e8-9f13-679ed009a664.png)
This is your screenshot from before, seems to be working for me. It appears that the card grid was not detected properly.
Are you using Windows 7 or 10?

**Comment by eoakley** [comment]
Just fixed this in the [latest release](https://github.com/eoakley/artifacthelper/releases/latest).

Try the new function "Customize Grid".

If you still have problems, open a new issue with the following:
* Description of your setup (monitor resolutions)
* Full screenshot (all monitors) 
* File **screenshot_debugg.png** from the install dir
* File Artifact_Helper.launch.pyw.log from the folder C:\Users\<your_user>\AppData\Roaming

Thanks for the help!
