### ISSUE TITLE
Card Detection not working with custom grid

### ISSUE THREAD

**Issue by IgorMCesar** [eoakley/artifacthelper#17]
Still only workinng on version 0.6. Tried the new feature "Custom Grid" and it still doesnt detect cards.
Dont know if its intended but when i set a new custom grid it only shows a black screen, not like the png your guys showed.
 
screenshot_debugg.png
![screenshot_debugg](https://user-images.githubusercontent.com/5064518/49535814-30b48380-f8ac-11e8-8d74-f2497f8ac285.png)

screenshot_draft.png
![screenshot_draft](https://user-images.githubusercontent.com/5064518/49535817-327e4700-f8ac-11e8-94fd-af62a16abc92.png)

<details>
<summary>Log Here</summary>
...And One For Me, Abaddon, Aghanim's Sanctum, Altar of the Mad Moon, Annihilation, Apotheosis Blade, Arcane Assault, Arcane Censure, Arm the Rebellion, Assassin's Apprentice, Assassin's Shadow, Assassin's Veil, Assured Destruction, At Any Cost, Avernus' Blessing, Axe, Barbed Mail, Beastmaster, Bellow, Better Late Than Never, Bitter Enemies, Blade of the Vigil, Blink Dagger, Bloodseeker, Bolt of Damocles, Book of the Dead, Bounty Hunter, Bracers of Sacrifice, Bristleback, Broadsword, Bronze Legionnaire, Burning Oil, Buying Time, Call the Reserves, Caught Unprepared, Centaur Warrunner, Chainmail, Champion of the Ancient, Cheating Death, Chen, Claszureme Hourglass, Claymore, Cleansing Rite, Clear the Deck, Cloak of Endless Carnage, Collateral Damage, Combat Training, Compel, Conflagration, Coordinated Assault, Corrosive Mist, Crippling Blow, Crystal Maiden, Cunning Plan, Curse of Atrophy, Cursed Satyr, Dark Seer, Defend the Weak, Defensive Bloom, Defensive Stance, Demagicking Maul, Diabolic Revelation, Dimensional Portal, Dirty Deeds, Disciple of Nevermore, Divine Intervention, Divine Purpose, Drow Ranger, Earthshaker, Emissary of the Quorum, Enchantress, Enough Magic!, Escape Route, Fight Through the Pain, Fog of War, Foresight, Forward Charge, Fractured Timeline, Friendly Fire, Fur-lined Mantle, Gank, Glyph of Confusion, Golden Ticket, Grand Melee, Grazing Shot, Hellbear Crippler, Helm of the Dominator, Hero's Cape, Heroic Resolve, Hip Fire, Homefield Advantage, Horn of the Alpha, Howling Mind, Incarnation of Selemene, Intimidation, Iron Branch Protection, Iron Fog Goldmine, Jasper Daggers, Juke, Kanna, 
------
Collected, 100 prices.

Keenfolk Golem, Keenfolk Musket, Keenfolk Plate, Keenfolk Turret, Legion Commander, Legion Standard Bearer, Lich, Lightning Strike, Lion, Lodestone Demolition, Lost in Time, Luna, Lycan, Magnus, Marrowfell Brawler, Mazzie, Meepo, Mercenary Exiles, Messenger Rookery, Mist of Avernus, Murder Plot, Necrophos, New Orders, Nyctasha's Guard, Obliterating Orb, Oglodi Catapult, Oglodi Vandal, Ogre Conscript, Ogre Corpse Tosser, Ogre Magi, Omniknight, Outworld Devourer, Path of the Bold, Path of the Cunning, Path of the Dreamer, Path of the Wise, Payday, Phantom Assassin, Phase Boots, Pick a Fight, Pick Off, Pit Fighter of Quoidge, Platemail, Poaching Knife, Poised to Strike, Prellex, Pugna, Rampaging Hellbear, Ravenhook, Ravenous Mass, Raze, Rebel Decoy, Rebel Instigator, Red Mist Maul, Red Mist Pillager, Relentless Pursuit, Relentless Zombie, Remote Detonation, Rend Armor, Restoration Effort, Revtel Convoy, Revtel Investments, Revtel Signet Ring, Ring of Tarrasque, Rising Anger, Ristul Emblem, Rix, Rolling Storm, Roseleaf Rejuvenator, Routed, Rumusque Blessing, Rumusque Vestments, Satyr Duelist, Satyr Magician, Selemene's Favor, Self Sabotage, Selfish Cleric, Seraphim Shield, Shield of Aquila, Shield of Basilius, Shiva's Guard, Shop Deed, Sister of the Veil, Skywrath Mage, Slay, Smash Their Defenses!, Smeevil Armsmaster, Smeevil Blacksmith, Sniper, Sorla Khan, Soul of Spring, Spot Weakness, Spring the Trap, Stars Align, Steal Strength, Steam Cannon, Stonehall Cloak, Stonehall Elite, Stonehall Pike, Stonehall Plate, 
------
Collected, 200 prices.

Storm Spirit, Strafing Run, Sucker Punch, Sven, Temple of War, The Cover of Night, The Oath, The Omexe Arena, The Tyler Estate, Thunderhide Alpha, Thunderhide Pack, Thunderstorm, Tidehunter, Timbersaw, Time of Triumph, Tinker, Tower Barrage, Treant Protector, Trebuchets, Tresdin's Standards, Troll Soothsayer, Tyler Estate Censor, Unearthed Secrets, Unsupervised Artillery, Untested Grunt, Ursa, Venomancer, Ventriloquy, Vesture of the Tyrant, Vhoul Martyr, Viper, Watchtower, Whispers of Madness, Wingfall Hammer, Winter Wyvern, Wrath of Gold, Zeus, 
------
Collected, 237 prices.

Screenshot of the game
SS saved to file D:\l\ArtifactHelper2\screenshot_draft.png
Launching Grid Selector
Deleted file D:\l\ArtifactHelper2\custom_grid.npy
Creating overlay with size: 2560 1440
Detecting grid once... (1440, 2560, 3)
['Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card'] 
 Borders: (360, 853, 1280)
Screenshot of the game
SS saved to file D:\l\ArtifactHelper2\screenshot_draft.png
Launching Grid Selector
Grid selected manually and saved to file "D:\l\ArtifactHelper2\custom_grid.npy"
It will be loaded automatically when you scan cards.
Creating overlay with size: 2560 1440
Custom Grid file exists: D:\l\ArtifactHelper2\custom_grid.npy

Using custom grid with borders: [110, 160, 1810]
['Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card'] 
 Borders: [110, 160, 1810]

Using custom grid with borders: [110, 160, 1810]
['Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card'] 
 Borders: [110, 160, 1810]

Using custom grid with borders: [110, 160, 1810]
['Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card'] 
 Borders: [110, 160, 1810]

Using custom grid with borders: [110, 160, 1810]
['Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card'] 
 Borders: [110, 160, 1810]

Using custom grid with borders: [110, 160, 1810]

Using custom grid with borders: [110, 160, 1810]
['Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card'] 
 Borders: [110, 160, 1810]

Using custom grid with borders: [110, 160, 1810]
['Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card'] 
 Borders: [110, 160, 1810]

Using custom grid with borders: [110, 160, 1810]
['Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card'] 
 Borders: [110, 160, 1810]

Using custom grid with borders: [110, 160, 1810]

Using custom grid with borders: [110, 160, 1810]
['Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card'] 
 Borders: [110, 160, 1810]
['Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card'] 
 Borders: [110, 160, 1810]

Screenshot of the game
SS saved to file D:\l\ArtifactHelper2\screenshot_draft.png
Launching Grid Selector
Grid selected manually and saved to file "D:\l\ArtifactHelper2\custom_grid.npy"
It will be loaded automatically when you scan cards.
Creating overlay with size: 2560 1440
Custom Grid file exists: D:\l\ArtifactHelper2\custom_grid.npy

Using custom grid with borders: [105, 160, 1813]
['Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card'] 
 Borders: [105, 160, 1813]

Using custom grid with borders: [105, 160, 1813]
['Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card'] 
 Borders: [105, 160, 1813]

Using custom grid with borders: [105, 160, 1813]
['Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card'] 
 Borders: [105, 160, 1813]
Creating overlay with size: 2560 1440
Custom Grid file exists: D:\l\ArtifactHelper2\custom_grid.npy

Using custom grid with borders: [105, 160, 1813]
['Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card'] 
 Borders: [105, 160, 1813]

Using custom grid with borders: [105, 160, 1813]
['Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card'] 
 Borders: [105, 160, 1813]

Using custom grid with borders: [105, 160, 1813]
['Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card'] 
 Borders: [105, 160, 1813]

Using custom grid with borders: [105, 160, 1813]
['Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card'] 
 Borders: [105, 160, 1813]

Using custom grid with borders: [105, 160, 1813]
['Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card', 'Empty Card'] 
 Borders: [105, 160, 1813]
</details>

[EDIT]
Version 0.6 screen_shot_debugg.png

![screen_shot_debugg](https://user-images.githubusercontent.com/5064518/49536204-18913400-f8ad-11e8-9664-88dc09f38da0.png)

**Comment by eoakley** [comment]
Windows 7? On borderless window, right? Try windowed please.

**Comment by IgorMCesar** [comment]
Windows 10, tried windowed too. Same problem. I think if it werent borderless even v0.6 wouldnt work :/

**Comment by eoakley** [comment]
v0.6 takes a screenshot of the monitor. v0.7+ takes a screenshot of the game only, with no overlay on top. That part, for some reason, is not working in your setup.

**Comment by eoakley** [comment]
Try replacing the contents of the files screen_processor.py and artifact_helper.py with the new ones from https://github.com/eoakley/artifacthelper.

Should not work perfectly but its better than black screen.

**Comment by IgorMCesar** [comment]
Traceback (most recent call last):
  File "D:\ArtifactHelper3\Artifact_Helper.launch.pyw", line 31, in <module>
    from artifact_helper import main
  File "D:\ArtifactHelper3\pkgs\artifact_helper.py", line 1, in <module>
    from screen_processor import ScreenProcessor, numpy_flip, save_debugg_screenshot, grab_artifact
ImportError: cannot import name 'grab_artifact'

**Comment by eoakley** [comment]
Just updated it, can you copy again?

**Comment by IgorMCesar** [comment]
Works \o/

Ps: Valeu pela help, muito legal ver devs brasileiros fazendo esse tipo de projeto. Parabéns, de verdade =)

**Comment by eoakley** [comment]
Boa :) valeu por avisar, vou criar outra versão com essa change.
