### ISSUE TITLE
Don't work on my computer. Error detecting cards. 

### ISSUE THREAD

**Issue by cp287-zz** [eoakley/artifacthelper#18]
"Error detecting cards. Are you on draft screen? Try Customizing Grind. Saved screenshot_debugg.png on installation dir."

Still doesn't work on my computer.
Did Grid about 20 times, cant find cards anyway. 
It is difficult to make a grid, because the artifact application is under the grid, and you can’t see where to drag, you have to hold your finger to the point where to drag, which makes the process much less accurate.
Log file is empty, screenshots in attach.

![screenshot_debugg](https://user-images.githubusercontent.com/41448687/49536343-65750a80-f8ad-11e8-8860-b963c29d711e.png)
![screenshot_draft](https://user-images.githubusercontent.com/41448687/49536346-673ece00-f8ad-11e8-84f4-0f6feb5c45ab.png)

My system: windows 7, two monitors, resolutions: 1920x1080 and 1600x1200. Artifact on first one with resolution 1440x960 16:10 borderless.

**Comment by zhdan84** [comment]
Same problem for me:
Single monitor, tried 1920x1080 and 1690x800 in both borderless and windowed modes. Win 10 Enterprise
tried customized - no luck. 
launching as admin,

**Comment by eoakley** [comment]
Can one of you try the following:
Edit the file pkgs/screen_processor.py

Change line 212 from

`    left, top, right, bot = win32gui.GetClientRect(hwnd)`

to

`    left, top, right, bot = win32gui.GetWindowRect(hwnd)`

Change line 228 from

`result = windll.user32.PrintWindow(hwnd, saveDC.GetSafeHdc(), 1)`

to

`result = windll.user32.PrintWindow(hwnd, saveDC.GetSafeHdc(), 0)`

**Comment by zhdan84** [comment]
Didn't work for me. Should customize grid screen be black, white or show the screen?
mine showed all black like on first comment, then I played with steam overlay settings and now its all white
.
it just seems that app cant see the screen at all

**Comment by eoakley** [comment]
Should show the game screen.

**Comment by zhdan84** [comment]
![screenshot_debugg](https://user-images.githubusercontent.com/45642702/49552253-9ce0b880-f8a7-11e8-8018-2c105eb84466.png)

**Comment by eoakley** [comment]
Try replacing the contents of the files screen_processor.py and artifact_helper.py with the new ones from https://github.com/eoakley/artifacthelper.

Should not work perfectly but its better than black screen.

**Comment by cp287-zz** [comment]
With new files program doesn't launch with success for me.
At log file:
"Traceback (most recent call last):
  File "E:\Users\4Game\AppData\Local\Artifact Helper\Artifact_Helper.launch.pyw", line 31, in <module>
    from artifact_helper import main
  File "E:\Users\4Game\AppData\Local\Artifact Helper\pkgs\artifact_helper.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax"

**Comment by eoakley** [comment]
Please try again. Thanks.

**Comment by zhdan84** [comment]
it is working now for me. thanks a lot!
