### ISSUE TITLE
It does work now but still a few major issues

### ISSUE THREAD

**Issue by zeroguz** [eoakley/artifacthelper#19]
![image](https://user-images.githubusercontent.com/36460450/49543546-cebe4300-f8d8-11e8-9db1-617b9d874968.png)
 
this problem happens, when you set your dispay size to 125% or greater in windows, (which alot of people do on small laptops)

another issue is, that if i tab out of the draft the helper doesnt stick to the game, but instead follows onto the browser, or whatever i tab to

**Comment by zeroguz** [comment]
the first screenshot is the FULL grid selection window, im 99% certain its 125% bigger then it needs to be because of windows text size things

**Comment by eoakley** [comment]
Can you try the following:
Right click the Artifact Helper shortcut on the Start menu -> Open file location
Right click the Artifact Helper shortcut -> Compatibility tab -> Change high DPI settings -> High DPI scaling override [x] check it and select Application

Do that and report back please. Thanks
