### ISSUE TITLE
Overlay postition depends on launch window position

### ISSUE THREAD

**Issue by BudgieInWA** [eoakley/artifacthelper#2]
When I switching from the Launch Window to the overlay, the window doesn't move and so the overlay is offset towards the bottom right (depending on the position of the original window). These screenshots demonstrate it.

Notice the position of the top left corner of the launch window:
![artifacthelper launch window](https://user-images.githubusercontent.com/3784591/49335048-2e3df980-f620-11e8-9516-176f0598d45c.PNG)

Notice the the overlay is starting at that same location:
![artifacthelper overlay](https://user-images.githubusercontent.com/3784591/49335050-4ada3180-f620-11e8-80f9-75d7da1ca49a.PNG)

(Also of note, the overlay is in the screenshot, so it covers up the names of some cards which aren't recognised. The overlay in this position would actually cause the `right_border` to fail, but I hard coded that during theses tests.)

If I move the Launch Window, launch the Overlay, then close the Overlay, the Launch Window *does* return to its hard coded size/location.

---

It looks like [this `root.geometry()` call](https://github.com/eoakley/artifacthelper/blob/e7e6d34b75cd8fdf6f5a56bfb3000a164bb28354/artifact_helper.py#L243) is failing to set the position. No matter what numbers I put in place of `(100, 0)`, the overlay origin is always the same as the top left of the launch window.

As a **workaround** I position the launch window at `(100, 0)` on [line 280](https://github.com/eoakley/artifacthelper/blob/e7e6d34b75cd8fdf6f5a56bfb3000a164bb28354/artifact_helper.py#L280) and don't move it.

**Comment by Miojo** [comment]
Helo BudgieInWA , Thanks for the input.

The issue seems to be related to tkinter .

What resolution is your monitor? 
Are you building the code locally or using the Installer? If building locally what is your python version?

**Comment by Miojo** [comment]
New version has a button to drag the overlay, it will help with this issue while we can't pinpoint the error.

**Comment by BudgieInWA** [comment]
> Are you building the code locally or using the Installer?

I am using installer v0.6 and editing `pkgs/artifact_helper.py` etc. in place.

My monitor is 1920 * 1080.

**Comment by eoakley** [comment]
Please give it another shot on the [latest release](https://github.com/eoakley/artifacthelper/releases/latest).

If you still have problems, open a new issue with the following:
* Description of your setup
* Full screenshot (all monitors) 
* File **screen_shot_debugg.png** from the install dir

Thanks for the help

**Comment by BudgieInWA** [comment]
It is strange that `root.geometry('+x+y')` works for the dragging but not while the overlay is being constructed. In any case, I can run `root.geometry('+100+0')` [when the scan button is clicked](https://github.com/eoakley/artifacthelper/blob/5fee9dd8965b875344a2d039e8df7e656ede3d74/artifact_helper.py#L163) and it repositions the window correctly!

Maybe this particular bug can be worked around by adding `if outOfPosition(root): root.geometry(...)` to the scan button. Maybe the overlay should always be exactly root.geometry("{}x{}+{}+{}".format(screen_width, screen_height, 0, 0))` with the position of the banner and cards positioned relative to the card bounding box. If that was true, #10 could still be used to locate the cards on screen, but without moving the window.
