### ISSUE TITLE
not displaying with correct spacing

### ISSUE THREAD

**Issue by wakamex** [eoakley/artifacthelper#21]
i can now set up a custom grid that works, but only by dragging off the popup screen, which is too zoomed in

afterward it seems to detect cards properly, but doesn't display them in the right places

setup
- 4k 1 monitor (3840x2160)
- "Change the size of text, apps, and other items": 150% (Recommend)
- screen_shot_debugg.png not created, because detection doesn't trigger an error
- screenshot_draft.png is updated, included below, shows similar zoom-in as custom grid popup screen

windows display screen
![image](https://user-images.githubusercontent.com/16990562/49619357-439d8580-f98a-11e8-836d-99b7dae8ee1a.png)

custom grid popup screen
![image](https://user-images.githubusercontent.com/16990562/49619279-ed304700-f989-11e8-97c5-be8cea484ea3.png)

draft screen
![image](https://user-images.githubusercontent.com/16990562/49619180-75621c80-f989-11e8-8553-1060749497ad.png)

screenshot_draft.png
![screenshot_draft](https://user-images.githubusercontent.com/16990562/49619415-7fd0e600-f98a-11e8-8e5d-5257832ff36f.png)

**Comment by eoakley** [comment]
Can you try the following:
Right click the Artifact Helper shortcut on the Start menu -> Open file location
Right click the Artifact Helper shortcut -> Compatibility tab -> Change high DPI settings -> High DPI scaling override [x] check it and select Application

Do that and report back please. Thanks

**Comment by wakamex** [comment]
that worked to position the overlay correctly!
![image](https://user-images.githubusercontent.com/16990562/49630746-7d3bb400-f9bd-11e8-97ac-493fec4cfff2.png)

although correctly positioned, the boxes seem to be a bit shrunk
![image](https://user-images.githubusercontent.com/16990562/49630821-c7249a00-f9bd-11e8-8e94-367186fa462f.png)

**Comment by wakamex** [comment]
the latest release v1.1 solved the display problem
