### ISSUE TITLE
the percentages are off

### ISSUE THREAD

**Issue by kanyipi** [eoakley/artifacthelper#27]
the percentages are not one the cards. they divide the screen into 6 parts and each percentage has its own

**Comment by eoakley** [comment]
Can you post a sceenshot?

**Comment by kanyipi** [comment]
![Uploading artif.png…](here)

**Comment by kanyipi** [comment]
![artif](https://user-images.githubusercontent.com/29727057/49702737-c8d7a300-fbf3-11e8-94de-4d94af0a88e6.png)
sorry i messed up the last here it is

**Comment by eoakley** [comment]
Are you using Windows scale options? 

"If you are using Windows scale options (zooms text, apps, icons), you need to disable it by right clicking the Artifact Helper shortcut -> Compatibility tab -> Change high DPI settings -> check High DPI scaling override and select Application"

**Comment by kanyipi** [comment]
Thank you
