### ISSUE TITLE
See updated Tier list here. Paste this into your tier_list.txt

### ISSUE THREAD

**Issue by JackFlaxton** [eoakley/artifacthelper#29]
#################################################################################################################################
# This file represents your tier list file. Default values are taken from https://drawtwo.gg/hypeds-limited-tier-list           #
# Tiers vary from S to F (S is the strongest) and each tier has an inside tier rank (1 is the best position inside the tier)    #
# Besides the tier and tier rank values you can also customize a custom value for each card that will be printed on the screen  #
#################################################################################################################################
# HEROES:
#card name; tier; tier rank; custom rank
Abaddon;C;14;
Axe;S;1;
Beastmaster;B;2;
Bloodseeker;C;2;
Bounty Hunter;A;5;
Bristleback;B;1;
Centaur Warrunner;C;7;
Chen;B;5;
Crystal Maiden;D;1;
Dark Seer;C;1;
Debbi the Cunning;C;2;
Drow Ranger;S;2;
Earthshaker;B;14;
Enchantress;B;3;
Farvhan the Dreamer;C;5;
J'Muy the Wise;C;4;
Kanna;S;3;
Keefe the Bold;D;11;
Legion Commander;S;6;
Lich;S;4;
Lion;D;4;
Luna;B;4;
Lycan;A;2;
Magnus;B;8;
Mazzie;C;3;
Meepo;F;2;
Necrophos;C;6;
Ogre Magi;A;6;
Omniknight;A;3;
Outworld Devourer;F;4;
Phantom Assassin;A;2;
Prellex;C;13;
Pugna;D;3;
Rix;F;3;
Skywrath Mage;C;10;
Sniper;A;7;
Sorla Khan;A;1;
Storm Spirit;F;1;
Sven;C;9;
Tidehunter;D;12;
Timbersaw;C;10;
Tinker;S;3;
Treant Protector;A;8;
Ursa;B;7;
Venomancer;B;7;
Viper;D;9;
Winter Wyvern;C;3;
Zeus;B;8;
#################################################################################################################################
# MAIN:
#card name; tier; tier rank; custom rank
...And One For Me;C;10;
Aghanim's Sanctum;A;6;
Altar of the Mad Moon;C;25;
Annihilation;S;4;
Arcane Assault;C;9;
Arcane Censure;F;12;
Arm the Rebellion;A;25;
Assassin's Apprentice;B;23;
Assassin's Shadow;B;38;
Assured Destruction;D;22;
At Any Cost;A;4;
Avernus' Blessing;C;19;
Bellow;D;28;
Better Late Than Never;D;12;
Bitter Enemies;D;21;
Bolt of Damocles;B;37;
Bronze Legionnaire;A;7;
Burning Oil;B;28;
Buying Time;D;13;
Call the Reserves;D;18;
Caught Unprepared;C;7;
Champion of the Ancient;B;2;
Cheating Death;B;12;
Cleansing Rite;F;13;
Clear The Deck;B;16;
Collateral Damage;D;25;
Combat Training;C;20;
Compel;B;6;
Conflagration;S;8;
Coordinated Assault;A;23;
Corrosive Mist;C;24;
Crippling Blow;D;7;
Cunning Plan;B;7;
Curse of Atrophy;C;27;
Cursed Satyr;C;17;
Defend the Weak;B;34;
Defensive Bloom;B;26;
Defensive Stance;F;1;
Diabolic Revelation;D;10;
Dimensional Portal;A;1;
Dirty Deeds;F;9;
Disciple of Nevermore;A;13;
Divine Intervention;B;14;
Divine Purpose;D;32;
Emissary of the Quorum;S;5;
Enough Magic!;B;29;
Escape Route;C;22;
Fight Through The Pain;D;1;
Fog of War;D;16;
Foresight;B;5;
Forward Charge;D;23;
Fractured Timeline;C;11;
Friendly Fire;A;8;
Gank;A;15;
Glyph of Confusion;D;19;
Grand Melee;F;2;
Grazing Shot;C;18;
Hellbear Crippler;B;39;
Heroic Resolve;D;3;
Hip Fire;B;13;
Homefield Advantage;B;31;
Howling Mind;D;14;
Incarnation of Selemene;B;10;
Intimidation;B;33;
Iron Branch Protection;D;29;
Iron Fog Goldmine;A;9;
Juke;D;27;
Keenfolk Golem;C;26;
Keenfolk Turret;B;15;
Legion Standard Bearer;A;29;
Lightning Strike;C;16;
Lodestone Demolition;F;10;
Lost in Time;B;32;
Marrowfell Brawler;A;18;
Mercenary Exiles;A;28;
Messenger Rookery;B;27;
Mist of Avernus;S;1;
Murder Plot;B;3;
New Orders;C;14;
Oglodi Catapult;F;8;
Oglodi Vandal;A;16;
Ogre Conscript;A;12;
Ogre Corpse Tosser;B;21;
Path of the Bold;D;5;
Path of the Cunning;F;11;
Path of the Dreamer;D;30;
Path of the Wise;D;15;
Payday;B;19;
Pick A Fight;C;15;
Pick Off;A;22;
Pit Fighter of Quoidge;B;22;
Poised to Strike;D;2;
Rampaging Hellbear;C;4;
Ravenhook;D;26;
Ravenous Mass;C;21;
Raze;D;8;
Rebel Decoy;B;1;
Rebel Instigator;C;2;
Red Mist Pillager;A;3;
Relentless Pursuit;B;9;
Relentless Zombie;C;3;
Remote Detonation;B;30;
Rend Armor;F;3;
Restoration Effort;F;14;
Revtel Convoy;A;27;
Revtel Investments;C;8;
Rising Anger;D;4;
Rolling Storm;F;6;
Roseleaf Rejuvenator;B;11;
Routed;D;9;
Rumusque Blessing;A;20;
Satyr Duelist;B;20;
Satyr Magician;B;8;
Selemene's Favor;B;18;
Self Sabotage;D;17;
Selfish Cleric;A;24;
Sister of the Veil;B;25;
Slay;B;4;
Smash Their Defenses!;B;35;
Smeevil Armsmaster;C;6;
Smeevil Blacksmith;D;31;
Soul of Spring;A;5;
Spot Weakness;C;23;
Spring the Trap;S;6;
Stars Align;C;13;
Steal Strength;A;19;
Steam Cannon;A;21;
Stonehall Elite;A;2;
Strafing Run;D;11;
Sucker Punch;C;5;
Temple of War;D;6;
The Cover of Night;C;28;
The Oath;A;10;
The Omexe Arena;B;17;
The Tyler Estate;D;24;
Thunderhide Alpha;B;24;
Thunderhide Pack;A;14;
Thunderstorm;A;11;
Time of Triumph;S;3;
Tower Barrage;B;36;
Trebuchets;D;20;
Tresdin's Standards;A;17;
Troll Soothsayer;A;26;
Tyler Estate Censor;S;7;
Unearthed Secrets;S;2;
Unsupervised Artillery;C;29;
Untested Grunt;C;30;
Ventriloquy;C;1;
Vhoul Martyr;C;12;
Watchtower;F;4;
Whispers of Madness;F;5;
Wrath of Gold;F;7;
#################################################################################################################################
# ITEMS:
#card name; tier; tier rank; custom rank
Apotheosis Blade;U;19;
Assassin's Veil;C;9;
Barbed Mail;U;2;
Blade of the Vigil;U;3;
Blink Dagger;A;2;
Book of the Dead;U;9;
Bracers of Sacrifice;B;8;
Broadsword;C;6;
Chainmail;U;4;
Claszureme Hourglass;B;2;
Claymore;U;13;
Cloak of Endless Carnage;U;12;
Demagicking Maul;B;1;
Fur-lined Mantle;C;3;
Golden Ticket;B;9;
Helm of the Dominator;B;1;
Hero's Cape;U;14;
Horn of the Alpha;B;4;
Jasper Daggers;B;6;
Keenfolk Musket;C;8;
Keenfolk Plate;U;7;
Leather Armor;C;11;
Nyctasha's Guard;U;20;
Obliterating Orb;U;10;
Phase Boots;C;2;
Platemail;U;15;
Poaching Knife;C;10;
Red Mist Maul;C;3;
Revtel Signet Ring;A;3;
Ring of Tarrasque;U;11;
Ristul Emblem;U;1;
Rumusque Vestments;U;8;
Seraphim Shield;C;6
Shield of Aquila;C;4;
Shield of Basilius;C;5;
Shiva's Guard;U;16;
Shop Deed;U;18;
Short Sword;B;5;
Stonehall Cloak;A;1;
Stonehall Pike;C;7;
Stonehall Plate;B;7;
Traveler's Cloak;A;4;
Vesture of the Tyrant;B;5;
Wingfall Hammer;U;17;
#################################################################################################################################

**Comment by eoakley** [comment]
Done.
