### ISSUE TITLE
Cannot detect cards.

### ISSUE THREAD

**Issue by emerald000** [eoakley/artifacthelper#3]
Unsure if I am doing something wrong or I hit a bug. Game is in 1600x900 (Borderless Windowed) running on Windows 10. I tried restarting both Artifact and the Helper with no changes. 

![Screenshot](https://i.imgur.com/E6V2V8d.jpg)

**Comment by zeroguz** [comment]
same here, sometimes its not even saying error but instead nothing happens

**Comment by Thmyris** [comment]
Use native borderless fullscreen and keep the helper window in the game area, above the cards.

**Comment by eoakley** [comment]
Please give it another shot on the [latest release](https://github.com/eoakley/artifacthelper/releases/latest).

If you still have problems, open a new issue with the following:
* Description of your setup
* Full screenshot (all monitors) 
* File **screen_shot_debugg.png** from the install dir

Thanks for the help
