### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Palaryel** [eoakley/artifacthelper#4]
Case 1 Laptop:  tried using both 1360x768 and 1280x720 resolutions (yes, borderless windowed was on), get an error either way

Case 2 Desktop: dual monitor setup, one monitor running on 1920x1080 (16:9) native, second monitor running on 1680x1050 (16:10) native, game is ran on the 16:9 monitor,  I don't get any error message,but nothing happens either (note: there is no error message regardless on which screen I am)

**Comment by eoakley** [comment]
Please give it another shot on the [latest release](https://github.com/eoakley/artifacthelper/releases/latest).

If you still have problems, open a new issue with the following:
* Description of your setup
* Full screenshot (all monitors) 
* File **screen_shot_debugg.png** from the install dir

Thanks for the help
