### ISSUE TITLE
When only 2 cards are remaining the program usually fails to recognize them

### ISSUE THREAD

**Issue by Thmyris** [eoakley/artifacthelper#5]
Had this happen 4/5 times. No matter where i move the helper window it fails to recognize the images.

1920x1080 borderless window, windows 7
![screen_shot_debugg](https://user-images.githubusercontent.com/14177706/49384182-8281d000-f72b-11e8-9860-1a23a7773884.png)

**Comment by eoakley** [comment]
Please give it another shot on the [latest release](https://github.com/eoakley/artifacthelper/releases/latest).

If you still have problems, open a new issue with the following:
* Description of your setup
* Full screenshot (all monitors) 
* File **screen_shot_debugg.png** from the install dir

Thanks for the help
