### ISSUE TITLE
Can only detect cards on one of my screens.

### ISSUE THREAD

**Issue by awayfc** [eoakley/artifacthelper#6]
As title, it works on my second monitor when i move artifact there, but not my primary one.

Both screens are running 1920x1080.

**Comment by eoakley** [comment]
Please give it another shot on the [latest release](https://github.com/eoakley/artifacthelper/releases/latest).

If you still have problems, open a new issue with the following:
* Description of your setup
* Full screenshot (all monitors) 
* File **screen_shot_debugg.png** from the install dir

Thanks for the help
