### ISSUE TITLE
Dont work on my resolution

### ISSUE THREAD

**Issue by cp287-zz** [eoakley/artifacthelper#7]
Unfortunately still doesn't work on my computer.
My system: windows 7, two monitors, resolutions: 1920x1080 and 1600x1200. Artifact on first one with resolution 1440x960 16:10 borderless.

Screen in attach:
![screen_shot_debugg](https://user-images.githubusercontent.com/41448687/49404672-42c0e580-f737-11e8-9040-1d0d0e7d12f0.png)
![artifact_issue1](https://user-images.githubusercontent.com/41448687/49404810-aa773080-f737-11e8-932e-6ef1f9fe09c3.png)

**Comment by eoakley** [comment]
Can you try using the same resolution as your monitor for the game? It should have no borders. In your case, 1920x1080.

**Comment by cp287-zz** [comment]
I dont know why but i dont have this one in game (yeah, it is strange :))
![artifact_issue2](https://user-images.githubusercontent.com/41448687/49407719-a7347280-f740-11e8-998a-15be62bd29ec.png)

**Comment by eoakley** [comment]
Try selecting 16:9

**Comment by cp287-zz** [comment]
sure I tried, by there max resolution is 1366x768 :(

**Comment by eoakley** [comment]
Just fixed this in the [latest release](https://github.com/eoakley/artifacthelper/releases/latest).

If you still have problems, open a new issue with the following:
* Description of your setup
* Full screenshot (all monitors) 
* File **screen_shot_debugg.png** from the install dir

Thanks for the help!
