### ISSUE TITLE
detects only 3 cards on 3840x2160

### ISSUE THREAD

**Issue by wakamex** [eoakley/artifacthelper#8]
only detects first 3 cards. not sure if it has to do with my resolution.

screenshot
<img width="1920" alt="screen_shot" src="https://user-images.githubusercontent.com/16990562/49407066-611de580-f725-11e8-9d04-23e2182c3760.png">

debug screen
![screen_shot_debugg](https://user-images.githubusercontent.com/16990562/49407075-68dd8a00-f725-11e8-9ea6-4ce0d66f981e.png)

default setup
![image](https://user-images.githubusercontent.com/16990562/49407114-8c083980-f725-11e8-8bfe-b8878f355612.png)

switching to this and hitting apply does nothing, then reverts to the above when re-opening the settings screen
![image](https://user-images.githubusercontent.com/16990562/49407240-e30e0e80-f725-11e8-9c20-05e896822fe1.png)

**Comment by eoakley** [comment]
Just fixed this in the [latest release](https://github.com/eoakley/artifacthelper/releases/latest).

If you still have problems, open a new issue with the following:
* Description of your setup
* Full screenshot (all monitors) 
* File **screen_shot_debugg.png** from the install dir

Thanks for the help!
