### ISSUE TITLE
21:9 3440x1440 support

### ISSUE THREAD

**Issue by NicolasConstant** [eoakley/artifacthelper#9]
Hello, I know that you're only supporting 16:9 right now but I managed to make it work on my own so here is some insight that may help you supporting 3440x1440 resolution (21:9). 

First here is the debug image: 
![screen_shot_debugg](https://user-images.githubusercontent.com/5437247/49415756-a3efb580-f745-11e8-9cb9-2424aa47f475.png)

At first the error message itself wasn't displaying (cropped in the center):
![error_message_missing](https://user-images.githubusercontent.com/5437247/49415784-bcf86680-f745-11e8-969c-dd50f5fd255c.png)

I have hard-coded the top_border, left_border, right_border (why don't you rely on presets instead of your calculations?) and changed the root.geometry() values and it fixed it:
![3440x1440_fixed](https://user-images.githubusercontent.com/5437247/49415872-fd57e480-f745-11e8-9b7f-338e98ef48b9.png)

Please find my modifications and values in [this commit](https://github.com/NicolasConstant/artifacthelper/commit/92c9ba983841c81dd8b96c23d7551c97a8e3a387).
It's my first time with a python project, but if I can help you in any way, let me know.

**Comment by eoakley** [comment]
Just fixed this in the [latest release](https://github.com/eoakley/artifacthelper/releases/latest).

If you still have problems, open a new issue with the following:
* Description of your setup
* Full screenshot (all monitors) 
* File **screen_shot_debugg.png** from the install dir

Thanks for the help!
